#pragma once

#include "lvgl.h"

// Auto-generated by scripts/gen_meat_icons.py — see src/img_meat_icons.c
LV_IMG_DECLARE(img_meat_chicken);
LV_IMG_DECLARE(img_meat_lamb);
LV_IMG_DECLARE(img_meat_pork);
LV_IMG_DECLARE(img_meat_beef);
